services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9000:9090"
    volumes:
      - ${PWD}/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ${PWD}/rules.yaml:/etc/prometheus/rules.yaml
  go-server:
    container_name: go-server
    image: vijayvepa/go-server
    ports:
    - "9001:8090"
  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    ports:
    - "9002:3000"
    volumes:
      - ${PWD}/grafana-data:/var/lib/grafana
  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager
    ports:
      - "9003:9093"
    volumes:
      - ${PWD}/alertmanager.yaml:/etc/alertmanager/alertmanager.yml 
  httpbin:
    container_name: httpbin
    image: kennethreitz/httpbin
    ports:
      - "9004:80"
  webhook:
    container_name: webhook
    image: lucascimon/nginx-logging-proxy
    depends_on:
      - httpbin
    environment:
      PROXIED_ENDPOINT: http://httpbin:80
      LISTENING_PORT: 8000
    ports:
      - "9005:8000"