global:
  scrape_interval: 15s
  evaluation_interval: 10s
rule_files:
  - rules.yaml
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - "localhost:9090"
  - job_name: server_go_http
    static_configs:
      - targets:
          - "go-server:8090"